# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/windowPlayers.ui'
#
# Created: Sun May 19 23:48:56 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_windowPlayers(object):
    def setupUi(self, windowPlayers):
        windowPlayers.setObjectName(_fromUtf8("windowPlayers"))
        windowPlayers.resize(800, 600)
        self.centralwidget = QtGui.QWidget(windowPlayers)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 80, 411, 471))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.verticalLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inputPlec = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.inputPlec.setObjectName(_fromUtf8("inputPlec"))
        self.gridLayout.addWidget(self.inputPlec, 4, 2, 1, 1)
        self.plec = QtGui.QLabel(self.verticalLayoutWidget)
        self.plec.setObjectName(_fromUtf8("plec"))
        self.gridLayout.addWidget(self.plec, 4, 0, 1, 1)
        self.inputImie = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.inputImie.setObjectName(_fromUtf8("inputImie"))
        self.gridLayout.addWidget(self.inputImie, 2, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 6, 2, 1, 1)
        self.inputNazw = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.inputNazw.setObjectName(_fromUtf8("inputNazw"))
        self.gridLayout.addWidget(self.inputNazw, 3, 2, 1, 1)
        self.rank = QtGui.QLabel(self.verticalLayoutWidget)
        self.rank.setObjectName(_fromUtf8("rank"))
        self.gridLayout.addWidget(self.rank, 5, 0, 1, 1)
        self.inputRank = QtGui.QTextBrowser(self.verticalLayoutWidget)
        self.inputRank.setObjectName(_fromUtf8("inputRank"))
        self.gridLayout.addWidget(self.inputRank, 5, 2, 1, 1)
        self.nazwisko = QtGui.QLabel(self.verticalLayoutWidget)
        self.nazwisko.setObjectName(_fromUtf8("nazwisko"))
        self.gridLayout.addWidget(self.nazwisko, 3, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.imie = QtGui.QLabel(self.verticalLayoutWidget)
        self.imie.setObjectName(_fromUtf8("imie"))
        self.gridLayout.addWidget(self.imie, 2, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 77))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.verticalLayoutWidget_2)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit = QtGui.QTextEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.pushButton_5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(470, 100, 302, 401))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoAction = QtGui.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infoAction.setFont(font)
        self.infoAction.setAlignment(QtCore.Qt.AlignCenter)
        self.infoAction.setObjectName(_fromUtf8("infoAction"))
        self.verticalLayout.addWidget(self.infoAction)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_8 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout.addWidget(self.pushButton_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_9 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout.addWidget(self.pushButton_9)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_10 = QtGui.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout.addWidget(self.pushButton_10)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        windowPlayers.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(windowPlayers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        windowPlayers.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(windowPlayers)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        windowPlayers.setStatusBar(self.statusbar)
        self.actionImportuj = QtGui.QAction(windowPlayers)
        self.actionImportuj.setObjectName(_fromUtf8("actionImportuj"))
        self.actionEksportuj = QtGui.QAction(windowPlayers)
        self.actionEksportuj.setObjectName(_fromUtf8("actionEksportuj"))
        self.actionZakoncz = QtGui.QAction(windowPlayers)
        self.actionZakoncz.setObjectName(_fromUtf8("actionZakoncz"))
        self.menuPlik.addAction(self.actionImportuj)
        self.menuPlik.addAction(self.actionEksportuj)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionZakoncz)
        self.menubar.addAction(self.menuPlik.menuAction())

        self.retranslateUi(windowPlayers)
        QtCore.QMetaObject.connectSlotsByName(windowPlayers)

    def retranslateUi(self, windowPlayers):
        windowPlayers.setWindowTitle(_translate("windowPlayers", "Gracze", None))
        self.plec.setText(_translate("windowPlayers", "Płeć", None))
        self.pushButton_6.setText(_translate("windowPlayers", "Następny", None))
        self.rank.setText(_translate("windowPlayers", "Nr w rankingu", None))
        self.nazwisko.setText(_translate("windowPlayers", "Nazwisko", None))
        self.pushButton_7.setText(_translate("windowPlayers", "Poprzedni", None))
        self.imie.setText(_translate("windowPlayers", "Imię", None))
        self.label.setText(_translate("windowPlayers", "Szukaj", None))
        self.pushButton_5.setText(_translate("windowPlayers", "Znajdź", None))
        self.infoAction.setText(_translate("windowPlayers", "Działanie na danych z formularza", None))
        self.pushButton_8.setText(_translate("windowPlayers", "Dodaj", None))
        self.pushButton_9.setText(_translate("windowPlayers", "Modyfikuj", None))
        self.pushButton_10.setText(_translate("windowPlayers", "Usuń", None))
        self.menuPlik.setTitle(_translate("windowPlayers", "Plik", None))
        self.actionImportuj.setText(_translate("windowPlayers", "Importuj", None))
        self.actionEksportuj.setText(_translate("windowPlayers", "Eksportuj", None))
        self.actionZakoncz.setText(_translate("windowPlayers", "Zakończ", None))

