# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/windowPlayers.ui'
#
# Created: Tue May 21 10:32:40 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_windowPlayers(object):
    def setupUi(self, windowPlayers):
        windowPlayers.setObjectName(_fromUtf8("windowPlayers"))
        windowPlayers.resize(800, 600)
        self.centralwidget = QtGui.QWidget(windowPlayers)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.horizontalLayout_3.addWidget(self.textEdit)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.inputPlec = QtGui.QTextBrowser(self.centralwidget)
        self.inputPlec.setObjectName(_fromUtf8("inputPlec"))
        self.gridLayout.addWidget(self.inputPlec, 4, 2, 1, 1)
        self.plec = QtGui.QLabel(self.centralwidget)
        self.plec.setObjectName(_fromUtf8("plec"))
        self.gridLayout.addWidget(self.plec, 4, 0, 1, 1)
        self.inputImie = QtGui.QTextBrowser(self.centralwidget)
        self.inputImie.setObjectName(_fromUtf8("inputImie"))
        self.gridLayout.addWidget(self.inputImie, 2, 2, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 6, 2, 1, 1)
        self.inputNazw = QtGui.QTextBrowser(self.centralwidget)
        self.inputNazw.setObjectName(_fromUtf8("inputNazw"))
        self.gridLayout.addWidget(self.inputNazw, 3, 2, 1, 1)
        self.rank = QtGui.QLabel(self.centralwidget)
        self.rank.setObjectName(_fromUtf8("rank"))
        self.gridLayout.addWidget(self.rank, 5, 0, 1, 1)
        self.inputRank = QtGui.QTextBrowser(self.centralwidget)
        self.inputRank.setObjectName(_fromUtf8("inputRank"))
        self.gridLayout.addWidget(self.inputRank, 5, 2, 1, 1)
        self.nazwisko = QtGui.QLabel(self.centralwidget)
        self.nazwisko.setObjectName(_fromUtf8("nazwisko"))
        self.gridLayout.addWidget(self.nazwisko, 3, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.imie = QtGui.QLabel(self.centralwidget)
        self.imie.setObjectName(_fromUtf8("imie"))
        self.gridLayout.addWidget(self.imie, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoAction = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.infoAction.setFont(font)
        self.infoAction.setAlignment(QtCore.Qt.AlignCenter)
        self.infoAction.setObjectName(_fromUtf8("infoAction"))
        self.verticalLayout.addWidget(self.infoAction)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout.addWidget(self.pushButton_8)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_9 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.verticalLayout.addWidget(self.pushButton_9)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout.addWidget(self.pushButton_10)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 1, 1, 1)
        windowPlayers.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(windowPlayers)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuPlik = QtGui.QMenu(self.menubar)
        self.menuPlik.setObjectName(_fromUtf8("menuPlik"))
        windowPlayers.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(windowPlayers)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        windowPlayers.setStatusBar(self.statusbar)
        self.actionImportuj = QtGui.QAction(windowPlayers)
        self.actionImportuj.setObjectName(_fromUtf8("actionImportuj"))
        self.actionEksportuj = QtGui.QAction(windowPlayers)
        self.actionEksportuj.setObjectName(_fromUtf8("actionEksportuj"))
        self.actionZakoncz = QtGui.QAction(windowPlayers)
        self.actionZakoncz.setObjectName(_fromUtf8("actionZakoncz"))
        self.menuPlik.addAction(self.actionImportuj)
        self.menuPlik.addAction(self.actionEksportuj)
        self.menuPlik.addSeparator()
        self.menuPlik.addAction(self.actionZakoncz)
        self.menubar.addAction(self.menuPlik.menuAction())

        self.retranslateUi(windowPlayers)
        QtCore.QMetaObject.connectSlotsByName(windowPlayers)

    def retranslateUi(self, windowPlayers):
        windowPlayers.setWindowTitle(QtGui.QApplication.translate("windowPlayers", "Gracze", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("windowPlayers", "Szukaj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("windowPlayers", "Znajdź", None, QtGui.QApplication.UnicodeUTF8))
        self.plec.setText(QtGui.QApplication.translate("windowPlayers", "Płeć", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("windowPlayers", "Następny", None, QtGui.QApplication.UnicodeUTF8))
        self.rank.setText(QtGui.QApplication.translate("windowPlayers", "Nr w rankingu", None, QtGui.QApplication.UnicodeUTF8))
        self.nazwisko.setText(QtGui.QApplication.translate("windowPlayers", "Nazwisko", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("windowPlayers", "Poprzedni", None, QtGui.QApplication.UnicodeUTF8))
        self.imie.setText(QtGui.QApplication.translate("windowPlayers", "Imię", None, QtGui.QApplication.UnicodeUTF8))
        self.infoAction.setText(QtGui.QApplication.translate("windowPlayers", "Działanie na danych z formularza", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("windowPlayers", "Dodaj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_9.setText(QtGui.QApplication.translate("windowPlayers", "Modyfikuj", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10.setText(QtGui.QApplication.translate("windowPlayers", "Usuń", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPlik.setTitle(QtGui.QApplication.translate("windowPlayers", "Plik", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportuj.setText(QtGui.QApplication.translate("windowPlayers", "Importuj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEksportuj.setText(QtGui.QApplication.translate("windowPlayers", "Eksportuj", None, QtGui.QApplication.UnicodeUTF8))
        self.actionZakoncz.setText(QtGui.QApplication.translate("windowPlayers", "Zakończ", None, QtGui.QApplication.UnicodeUTF8))

